In [1]:
import numpy as np

# Python list
lst = list(range(100000))
lst_result = [x * 5 for x in lst]

# NumPy array
arr = np.arange(100000)
arr_result = arr * 5

print("Both multiplied by 5 (NumPy is faster in real execution).")


Both multiplied by 5 (NumPy is faster in real execution).


In [2]:
a = np.arange(1, 11)
b = np.arange(1, 10).reshape(3, 3)

print("1D Array:", a)
print("2D Array:\n", b)

for x in [a, b]:
    print("Dimensions:", x.ndim)
    print("Shape:", x.shape)
    print("Size:", x.size)
    print("DataType:", x.dtype)
    print("Item size:", x.itemsize, "\n")

# Convert float array to int
float_arr = np.random.rand(3,3)
int_arr = float_arr.astype(int)
print("Float Array:\n", float_arr)
print("Converted to Int:\n", int_arr)


1D Array: [ 1  2  3  4  5  6  7  8  9 10]
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensions: 1
Shape: (10,)
Size: 10
DataType: int64
Item size: 8 

Dimensions: 2
Shape: (3, 3)
Size: 9
DataType: int64
Item size: 8 

Float Array:
 [[0.60273223 0.18797002 0.33037681]
 [0.67933403 0.06311169 0.00729938]
 [0.11790159 0.73030595 0.24242518]]
Converted to Int:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [5]:
print("Zeros:\n", np.zeros((4,4)))
print("Ones:\n", np.ones((3,2)))
print("Identity:\n", np.eye(5))
print("Constant 7:\n", np.full((2,3), 7))
print("Random Integers:\n", np.random.randint(10, 99, (3,4)))

arr = np.arange(5, 55, 6).reshape(3,3)
print("Arange and Reshape:\n", arr)


Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Identity:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Constant 7:
 [[7 7 7]
 [7 7 7]]
Random Integers:
 [[46 26 73 75]
 [22 61 92 64]
 [89 42 64 87]]
Arange and Reshape:
 [[ 5 11 17]
 [23 29 35]
 [41 47 53]]


In [8]:
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])

print("Second Row:", arr[1])
print("First 2 rows, last 2 columns:\n", arr[:2, 2:])
print("Last Column:", arr[:, -1])

arr[1] = [1, 2, 3, 4]
print("Modified Array:\n", arr)


Second Row: [50 60 70 80]
First 2 rows, last 2 columns:
 [[30 40]
 [70 80]]
Last Column: [ 40  80 120]
Modified Array:
 [[ 10  20  30  40]
 [  1   2   3   4]
 [ 90 100 110 120]]


In [12]:
A = np.random.randint(1, 10, 5)
B = np.random.randint(1, 10, 5)

print("A:", A)
print("B:", B)
print("Addition:", A + B)
print("Subtraction:", A - B)
print("Multiplication:", A * B)
print("Division:", A / B)

x = np.arange(1, 6)
print("Square Root:", np.sqrt(x))
print("Exponential:", np.exp(x))
print("Sine:", np.sin(x))

C = np.array([0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
F = (C * 9/5) + 32
print("Fahrenheit:", F)


A: [7 2 9 2 8]
B: [9 5 2 5 9]
Addition: [16  7 11  7 17]
Subtraction: [-2 -3  7 -3 -1]
Multiplication: [63 10 18 10 72]
Division: [0.77777778 0.4        4.5        0.4        0.88888889]
Square Root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Fahrenheit: [ 32.  50.  68.  86. 104. 122. 140. 158. 176. 194.]


In [13]:
A = np.arange(1, 10).reshape(3,3)

print("Add 10:\n", A + 10)
print("Add Row Vector:\n", A + np.array([1, 2, 3]))
print("Add Column Vector:\n", A + np.array([[1], [2], [3]]))


Add 10:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
Add Row Vector:
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
Add Column Vector:
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [14]:
arr = np.arange(1, 13)
print("3x4:\n", arr.reshape(3,4))
print("2x6:\n", arr.reshape(2,6))

a = np.arange(1, 10).reshape(3, 3)
flat = a.flatten()
rav = a.ravel()

flat[0] = 100
rav[1] = 200

print("Flattened:", flat)
print("Raveled:", rav)
print("Original after flatten:\n", a)   # no change
print("Original after ravel:\n", a)     # changes reflected


3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2x6:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Flattened: [100   2   3   4   5   6   7   8   9]
Raveled: [  1 200   3   4   5   6   7   8   9]
Original after flatten:
 [[  1 200   3]
 [  4   5   6]
 [  7   8   9]]
Original after ravel:
 [[  1 200   3]
 [  4   5   6]
 [  7   8   9]]
